# Generated by Django 4.0.4 on 2022-05-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='occurrence',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='user',
            new_name='added_by',
        ),
    ]
