# Generated by Django 4.0.4 on 2022-05-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0002_rename_user_file_added_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['category'], 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='App_1.attributecategory'),
            preserve_default=False,
        ),
    ]
