# Generated by Django 4.0.4 on 2022-05-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_alter_attribute_options_attribute_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['value'], 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
    ]
