# Generated by Django 4.0.4 on 2022-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0004_alter_attribute_options_remove_attribute_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['value__category'], 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterField(
            model_name='file',
            name='occurrence',
            field=models.ManyToManyField(blank=True, to='App_1.occurrence'),
        ),
        migrations.AlterField(
            model_name='file',
            name='site',
            field=models.ManyToManyField(blank=True, to='App_1.site'),
        ),
    ]
