# Generated by Django 4.0.4 on 2022-05-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0007_alter_attributechoice_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='AttributeOccurrence',
        ),
        migrations.AlterModelOptions(
            name='attributeoccurrence',
            options={'ordering': ['value__category', 'value'], 'verbose_name': 'Attribute', 'verbose_name_plural': 'Occurrence Attributes'},
        ),
        migrations.AlterModelTable(
            name='attributeoccurrence',
            table='attribute_occurrence',
        ),
        migrations.CreateModel(
            name='AttributeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_1.site')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='App_1.attributechoice')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Site Attributes',
                'db_table': 'attribute_site',
                'ordering': ['value__category', 'value'],
            },
        ),
    ]
