# Generated by Django 4.0.4 on 2022-05-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0009_alter_metric_auto_value_alter_metric_confirmed_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='auto_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='automatic value'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='confirmed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
