# Generated by Django 4.0.4 on 2022-05-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdi', '0002_file_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='test',
        ),
    ]
