# Generated by Django 4.0.4 on 2022-06-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi', '0003_remove_file_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-upload_date'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.RemoveConstraint(
            model_name='occurrence',
            name='Occurrence_location_and_or_bounding_polygon',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='creation_date',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='occurrence',
            old_name='location',
            new_name='position',
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.CheckConstraint(check=models.Q(('position__isnull', False), ('bounding_polygon__isnull', False), _connector='OR'), name='Occurrence_position_and_or_bounding_polygon'),
        ),
    ]
