# Generated by Django 2.2.24 on 2022-07-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20201107_2241'),
        ('archaeology', '0002_auto_20220726_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Document')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archaeology.Occurrence')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Occurrence Documents',
                'db_table': 'document_occurrence',
            },
        ),
        migrations.CreateModel(
            name='DocumentSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Document')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archaeology.Site')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Site Documents',
                'db_table': 'document_site',
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
