# Generated by Django 2.2.24 on 2022-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20201107_2241'),
        ('archaeology', '0004_auto_20220731_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributesite',
            name='site',
        ),
        migrations.RemoveField(
            model_name='attributesite',
            name='value',
        ),
        migrations.RemoveField(
            model_name='documentoccurrence',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentoccurrence',
            name='occurrence',
        ),
        migrations.RemoveField(
            model_name='documentsite',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentsite',
            name='site',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='attribute',
            field=models.ManyToManyField(blank=True, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='document',
            field=models.ManyToManyField(blank=True, to='archaeology.AttributeChoice'),
        ),
        migrations.AddField(
            model_name='site',
            name='attribute',
            field=models.ManyToManyField(blank=True, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='site',
            name='document',
            field=models.ManyToManyField(blank=True, to='archaeology.AttributeChoice'),
        ),
        migrations.DeleteModel(
            name='AttributeOccurrence',
        ),
        migrations.DeleteModel(
            name='AttributeSite',
        ),
        migrations.DeleteModel(
            name='DocumentOccurrence',
        ),
        migrations.DeleteModel(
            name='DocumentSite',
        ),
    ]
