# Generated by Django 2.2.24 on 2022-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0008_metric_unit_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='unit_measurement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='unit of measurement'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='attribute_occurrence',
            field=models.ManyToManyField(blank=True, to='archaeology.AttributeChoice', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='document_occurrence',
            field=models.ManyToManyField(blank=True, to='documents.Document', verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='site',
            name='attribute_site',
            field=models.ManyToManyField(blank=True, to='archaeology.AttributeChoice', verbose_name='a-ttributes'),
        ),
        migrations.AlterField(
            model_name='site',
            name='document_site',
            field=models.ManyToManyField(blank=True, to='documents.Document', verbose_name='documents'),
        ),
    ]
