# Generated by Django 2.2.24 on 2022-09-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0010_auto_20220904_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='resourcebase_ptr',
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
