# Generated by Django 2.2.24 on 2022-09-21 23:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0035_auto_20220223_1547'),
        ('archaeology', '0011_auto_20220904_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='status_occurrence',
            field=models.CharField(choices=[('A', 'Automatically Created'), ('C', 'Confirmed')], default='C', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='site',
            name='status_site',
            field=models.CharField(choices=[('A', 'Automatically Created'), ('C', 'Confirmed')], default='C', max_length=1, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='AlgorithmExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Executed at')),
                ('status', models.CharField(choices=[('E', 'Executing'), ('F', 'Finished')], default='E', max_length=1, verbose_name='Status')),
                ('aoi', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Area of Interest')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Executed by')),
                ('layers_used', models.ManyToManyField(to='layers.LayerFile', verbose_name='Layers Used')),
            ],
            options={
                'verbose_name': 'Algorithm Execution',
                'verbose_name_plural': 'Algorithm Executions',
                'db_table': 'algorithm_execution',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='occurrence',
            name='algorithm_execution',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archaeology.AlgorithmExecution', verbose_name='Created by execution'),
        ),
        migrations.AddField(
            model_name='site',
            name='created_by_execution',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archaeology.AlgorithmExecution', verbose_name='Created by execution'),
        ),
    ]
