# Generated by Django 2.2.24 on 2022-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0012_auto_20220921_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='status_occurrence',
            field=models.CharField(choices=[('N', 'Not Confirmed'), ('C', 'Confirmed')], default='C', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status_site',
            field=models.CharField(choices=[('N', 'Not Confirmed'), ('C', 'Confirmed')], default='C', max_length=1, verbose_name='Status'),
        ),
    ]
