# Generated by Django 2.2.24 on 2022-09-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0013_auto_20220921_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='status_occurrence',
            field=models.CharField(choices=[('N', 'Not Verified'), ('V', 'Verified')], default='V', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status_site',
            field=models.CharField(choices=[('N', 'Not Verified'), ('V', 'Verified')], default='V', max_length=1, verbose_name='Status'),
        ),
    ]
