# Generated by Django 2.2.24 on 2022-09-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0014_auto_20220921_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='status_occurrence',
            field=models.CharField(choices=[('N', 'Not Verified'), ('V', 'Verified'), ('T', 'Verified - True Positive'), ('F', 'Verified - False Positive')], default='V', max_length=1, verbose_name='Status'),
        ),
    ]
